name: Docker CI

on:
  push:
    branches:
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t 8byte-intern-app .
